#### System of linear equations (선형 연립 방정식)
- M개의 미지수를 가지는 N개의 선형 방정식
- 다음과 같이 간단하게 표현

$$Ax = b $$

$A, x, b$는 각각 계수 행렬, 미지수 벡터, 상수 벡터로 부른다.

#### 역행렬
- $A^{-1}A = AA^{-1} = I $
- 역행렬 존재 -> 가역행렬(invertable matrix)
- 존재x -> 특이행렬(singular matrix)

#### 역행렬의 성질

- 전치 행렬의 역행렬은 역행렬의 전치 행렬과 같다.

$$(A^T)^{-1} = (A^{-1})^T$$


- 두 개 이상의 정방 행렬의 곱은 같은 크기의 정방 행렬이 된다.

$$(ABC)^{-1} = C^{-1}B^{-1}C^{-1} $$

- C 는 cofactor matrix, $C^T$를 adjoint matrix ($adj(A)$ 로 표기)

$$A^{-1} = \dfrac{1}{\det A} C^T = \dfrac{1}{\det A} 
\begin{bmatrix}
C_{1,1} &\cdots& C_{N, 1}\\
\vdots &\ddots &\vdots\\
C_{1,N} &\cdots &C_{N,N}\\
\end{bmatrix}$$

위 식에서 **역행렬은 행렬식이 0이 아닌 경우에만 존재한다** 는 것을 알 수 있음



-
$C_{i,j}$은 마이너 값에 $(-1)^{i+j}$를 곱한 값. 즉, 

$$ C_{i,j} = (-1)^{i+j}M_{i,j} $$

-
$ M_{i,j} $는 마이너(minor, 소행렬식), 마이너 값도 행렬식
 






In [1]:
''' 
Ax = b 
x = A^(-1)b
'''

A = np.array([[2, 3, -2], [3, 5, 6], [2, 4, 3]])
A

array([[ 2,  3, -2],
       [ 3,  5,  6],
       [ 2,  4,  3]])

In [2]:
Ainv = np.linalg.inv(A)
Ainv

array([[ 0.69230769,  1.30769231, -2.15384615],
       [-0.23076923, -0.76923077,  1.38461538],
       [-0.15384615,  0.15384615, -0.07692308]])

In [3]:
b = np.array([[-5], [12], [7]])

In [4]:
x = np.dot(Ainv, b)
x

array([[-2.84615385],
       [ 1.61538462],
       [ 2.07692308]])

In [5]:
#최소자승법, np.linalg.inv 보다 선호됨
x, resid, rank, s = np.linalg.lstsq(A, b)
x

array([[-2.84615385],
       [ 1.61538462],
       [ 2.07692308]])

#### 역행렬의 존재
- 행렬식의 값이 0이 아니면 역행렬이 존재한다. 
- $det(A) =0 $ 일 경우 역행렬이 존재하지 않는다.

## 최소자승문제

방정식의 수가 미지수의 수보다 많은 데이터 분석의 특성상, 정확한 해가 존재하지 않을 수 있음

$$Ax \approx b $$

잔차 최소화

$$ e = Ax - b $$

잔차 벡터의 크기, 놈 최소화

$$ e^Te = \Vert e \Vert^2 = (Ax-b)^T(Ax-b) $$

함수를 가장 작게 만드는 x 값

$$ x = \text{arg} \min_x{e^Te} = \text{arg} \min_x{(Ax-b)^T(Ax-b)} $$

### 의사 역행렬(pseudo inverse) 

$$ Ax \approx b $$

가정
$$ A^TAx = A^Tb $$

$det(A^TA)^{-1}$ 이 0이 아니라 가정

$$ (A^TA)^{-1}(A^TA)x = (A^TA)^{-1}A^Tb $$

$$ x = ((A^TA)^{-1}A^T)b $$

A의 의사역행렬 $(A^TA)^{-1}A^T$, $A^+$로도 표기

$$A^+ = (A^TA)^{-1}A^T $$
