영 벡터가 아닌 모든 벡터 x $$ x^TAx > 0 $$
위 조건을 충족하는 경우 양-정부호(positive definite)
$$ x^TAx >= 0 $$ 이 조건인 경우에는 양-준정부호(positive semi-definite)

In [2]:
A = (np.arange(9) - 4).reshape(3, 3)
A

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

### Norm: use to check size of Matrix or Vector$$$$ 
Norm of A: $\|A\|$
$$\Vert A \Vert_L = \left( \sum_{i=1}^M \sum_{j=1}^N |a_{ij}|^L\right)^{1/L}$$
w/o significant L, usually L = 2
$$\Vert A \Vert = \Vert A \Vert_F = \sqrt {\sum_{i=1}^M \sum_{j=1}^N |a_{ij}^2}$$
F means Frobenius norm

In [2]:
np.linalg.norm(A)

7.745966692414834

In [3]:
print(np.eye(3)) # eye = identity matrix
np.trace(np.eye(3))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


3.0

#### trace = 대각합

In [3]:
np.trace(A)

0

$tr(cA) = c\:\ tr(A)$

$tr(A^T) = tr(A) $

$ tr(A + B) = tr(A) + tr(B) $

#### Trace trick

$tr(AB) = tr(BA)$

$tr(ABC) = tr(BCA) = tr(CAB)$

- quadratic form

$$ x^TAx = tr(x^TAx) = tr(Axx^T) = tr(xx^TA) $$


In [5]:
x = np.array([[1], [2]])
A = np.array([[1, 2], [2, 3]])
ans1 = np.dot(np.dot(x.T, A), x)
print(ans1)
ans2 = np.dot(np.dot(A, x), x.T)
print(ans2)
print(np.trace(ans1), np.trace(ans2))

[[21]]
[[ 5 10]
 [ 8 16]]
21 21


#### 행렬식 (determianant)
- 정방행렬 A의 행렬식은 det(A) 혹은 $\vert A \vert $ 로 표기된다.
- Cofactor(여인수) 전개로 불리는 재귀적 방법(recursive)으로 정의된다.


In [6]:
A = (np.arange(9)+1).reshape(3, 3)
np.linalg.det(A)

-9.5161973539299405e-16

#### 행렬식은 다음과 같은 성질을 만족
$$det(A^T) = det(A) $$

$$det(I) = 1 $$

$$det(AB) = det(A)det(B) $$

$$det(A^{-1}) = \dfrac {1}{\det(A)} $$

In [7]:
A2 = np.linalg.inv(A)
A2

array([[  3.15251974e+15,  -6.30503948e+15,   3.15251974e+15],
       [ -6.30503948e+15,   1.26100790e+16,  -6.30503948e+15],
       [  3.15251974e+15,  -6.30503948e+15,   3.15251974e+15]])