### numpy tutorial
http://aikorea.org/cs231n/python-numpy-tutorial/

- index

In [1]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [2]:
row_r1 = a[1, :]
row_r1, row_r1.shape

(array([5, 6, 7, 8]), (4,))

### 정수 배열 인덱싱
- 원본과 다른 배열을 만들 수 있음

In [3]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)
print("\n", a[[0,1], [1,0]])
a[[0,1,2], [0,1,0]], np.array([a[0,0], a[1,1], a[2,0]])

[[1 2]
 [3 4]
 [5 6]]

 [2 3]


(array([1, 4, 5]), array([1, 4, 5]))

In [4]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.array([0,2,0,1])
print(a, "\n\n" , b)
print("\n", a[np.arange(4), b])
a[np.arange(4), b] +=10
a

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

 [0 2 0 1]

 [ 1  6  7 11]


array([[11,  2,  3],
       [ 4,  5, 16],
       [17,  8,  9],
       [10, 21, 12]])

### Calculate

In [5]:
ls = [1,2,3,4,5]
na = np.array(ls)
na *= 3 
print(type(na), na)

<class 'numpy.ndarray'> [ 3  6  9 12 15]


In [7]:
na == 9, na > 10

(array([False, False,  True, False, False], dtype=bool),
 array([False, False, False,  True,  True], dtype=bool))

In [9]:
# 2의 배수만 남기기 - boolean 리스트를 offset으로
idx = na % 2 ==0
print(idx)
print(na[idx])

[False  True False  True False]
[ 6 12]


In [11]:
# 리스트에서 같은 수 추출하기
na1 = np.array([1,2,3,4,5])
na2 = np.array([1,3,3,4,4])
print(na1 == na2)
print(na1[na1 == na2])

[ True False  True  True False]
[1 3 4]


In [12]:
# 전체 리스트 비교하기
na1 = np.array([1,2,3,4,5])
na2 = np.array([1,3,3,4,4])
na3 = np.array([1,2,3,4,5])
print(np.all(na1 == na2))
print(np.all(na1 == na3))

False
True


###  broadcasting
- shape가 다른 배열 간에도 산술 연산 가능
- 코드를 간결하는데 유용

In [61]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
y = np.array([1, 0, 1]) # 벡터 y를 행렬 x 각 행에 더하려고 함
yy = np.tile(y, (4, 1)) # y의 복사본 4개를 쌓은 것이 yy
yy = x + yy
yy

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [62]:
# broadcasting
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
y = np.array([1, 0, 1]) 
yy = x + y
yy

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

두 배열의 브로드캐스팅은 아래의 규칙을 따릅니다:

- 두 배열이 동일한 rank를 가지고 있지 않다면, 낮은 rank의 1차원 배열이 높은 rank 배열의 shape로 간주합니다.
- 특정 차원에서 두 배열이 동일한 크기를 갖거나, 두 배열 중 하나의 크기가 1이라면 그 두 배열은 특정 차원에서 compatible하다고 여겨집니다.
- 두 행렬이 모든 차원에서 compatible하다면, 브로드캐스팅이 가능합니다.
- 브로드캐스팅이 이뤄지면, 각 배열 shape의 요소별 최소공배수로 이루어진 shape가 두 배열의 shape로 간주합니다.
- 차원에 상관없이 크기가 1인 배열과 1보다 큰 배열이 있을 때, 크기가 1인 배열은 자신의 차원 수만큼 복사되어 쌓인 것처럼 간주합니다.


In [94]:
#example

#벡터 외적 계산

v = np.array([1, 2, 3])
w = np.array([4, 5])
v_t = np.reshape(v, (3, 1))
print(v_t)
print("v.T * w : \n ", v_t * w, "\n")

# 벡터를 행렬의 각 행에 더하기

x = np.array([[1, 2, 3], [4, 5, 6]])
print("x + v : \n", x + v, "\n")

print("(x.T + w).T : \n",x.T,"\n" , (x.T + w).T, "\n")

print("x + w.T : \n", x+ np.reshape(w, (2, 1)))

[[1]
 [2]
 [3]]
v.T * w : 
  [[ 4  5]
 [ 8 10]
 [12 15]] 

x + v : 
 [[2 4 6]
 [5 7 9]] 

(x.T + w).T : 
 [[1 4]
 [2 5]
 [3 6]] 
 [[ 5  6  7]
 [ 9 10 11]] 

x + w.T : 
 [[ 5  6  7]
 [ 9 10 11]]


In [24]:
na1 = np.arange(12)
na2 = na1.reshape(3, 4)
print("na1 : \n{}".format(na1))
print("na2 : \n{}".format(na2))

na3 = np.ones_like(na1)
na3 = na3.reshape(3,4)
print("na3 : \n{}".format(na3))

print("na2 + 1 :\n{}".format(na2 + 1))
print("na2 + 1 :\n{}".format(na2 + na3))

na1 : 
[ 0  1  2  3  4  5  6  7  8  9 10 11]
na2 : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
na3 : 
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
na2 + 1 :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
na2 + 1 :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


##### functions
- min, max, argmin, argmax
- sum, mean, median, std, var
- all, any
- quartile
- exp, log

In [29]:
r = np.random.rand(2,3)
r_num = np.arange(5)
r_num = (r*10).astype('int64')
print("random matrix : \n{}".format(r_num))
print("min : {}".format(r_num.min()))
print("max : {}".format(r_num.max()))
print("argmin : {}".format(r_num.argmin())) # 최소값 위치
print("argmax : {}".format(r_num.argmax())) # 최대값 위치
print("mean : {}".format(r_num.mean()))

random matrix : 
[[3 9 4]
 [9 0 7]]
min : 0
max : 9
argmin : 4
argmax : 1
mean : 5.333333333333333


https://docs.scipy.org/doc/numpy/reference/routines.math.html
- math function

In [54]:
r = np.random.rand(2,3)
r_num = np.arange(5)
r_num = (r*10).astype('int64')
print("random matrix : \n{}".format(r_num))
print("sum : {}".format(np.sum(r_num)))
print("sum_axis_0 : {}".format(np.sum(r_num, axis=0)))
print("sum_axis_1 : {}".format(np.sum(r_num, axis=1)))
print("median : {}".format(np.median(r_num)))
print("std : {}".format(np.std(r_num))) # standard deviation (표준편차)
print(np.std(r_num) **2)
print("var : {}".format(np.var(r_num))) # variance (분산)

random matrix : 
[[8 7 3]
 [7 3 7]]
sum : 35
sum_axis_0 : [15 10 10]
sum_axis_1 : [18 17]
median : 7.0
std : 2.034425935955617
4.13888888889
var : 4.138888888888888


In [26]:
# quartile (사분위수)
na = np.array([num for num in range(0,101)])
print(na)
np.percentile(na, 25), np.percentile(na, 45)  

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


(25.0, 45.0)

#### exponential, log function

In [38]:
na = np.arange(1, 90, 30)
print(na)
print(np.exp(na),"\n", np.log(na))

[ 1 31 61]
[  2.71828183e+00   2.90488497e+13   3.10429794e+26] 
 [ 0.          3.4339872   4.11087386]


#### performance

In [39]:
ls = []
size = int(1E7)
for data in range(size):
    ls.append(data)
na = np.array(ls)

In [41]:
%%time
count = 0
for idx in range(len(ls)):
    if(ls[idx] % 3 == 0) or (ls[idx] % 5 == 0 ):
        count += 1
print(count)

4666667
CPU times: user 3.73 s, sys: 2.6 ms, total: 3.73 s
Wall time: 3.73 s


In [42]:
%%time
count = len(na[(na%3 == 0) | (na%5 == 0)])
print(count)

4666667
CPU times: user 496 ms, sys: 128 ms, total: 624 ms
Wall time: 653 ms


In [47]:
a = na[(na%3 == 0) | (na%5 == 0)]
len(a), a

(4666667, array([      0,       3,       5, ..., 9999995, 9999996, 9999999]))

- np.c_ (colum +)
- np.r_ (row +)

In [48]:
np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [49]:
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([1, 2, 3, 4, 5, 6])