- ndim : 차원 dimension
- shape: 모양 

In [1]:
array = np.array([0, 1, 2, 3])
print(type(array), array)
array.ndim, array.shape

<class 'numpy.ndarray'> [0 1 2 3]


(1, (4,))

#### np.arange 
- better than range()

#### np.newaxis
- increase the dimension
- can be used by 'None'


In [7]:
a = np.arange(6)[:, np.newaxis]
print(a.ndim, a.shape)
a

2 (6, 1)


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [3]:
array = np.array([0, 1, 2, 3])[:, np.newaxis]
array, array.shape

(array([[0],
        [1],
        [2],
        [3]]), (4, 1))

In [4]:
array = np.array([0, 1, 2, 3])[None, None, :] # None = np.newaxis
array, array.shape

(array([[[0, 1, 2, 3]]]), (1, 1, 4))

In [5]:
a = np.ones((2, 3, 6))
b = np.ones((2, 6))
print(a.shape,  b.shape, "\n")
print(a, "\n")
print("b", b, "\n")
print("b'", b[:, None,  :])
c = (a + b[:, np.newaxis, :])
c.shape, c

(2, 3, 6) (2, 6) 

[[[ 1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.]]] 

b [[ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]] 

b' [[[ 1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.]]]


((2, 3, 6), array([[[ 2.,  2.,  2.,  2.,  2.,  2.],
         [ 2.,  2.,  2.,  2.,  2.,  2.],
         [ 2.,  2.,  2.,  2.,  2.,  2.]],
 
        [[ 2.,  2.,  2.,  2.,  2.,  2.],
         [ 2.,  2.,  2.,  2.,  2.,  2.],
         [ 2.,  2.,  2.,  2.,  2.,  2.]]]))

#### reshape

In [8]:
a = a.reshape(3, 2)
print(a.ndim, a.shape)
a

2 (3, 2)


array([[0, 1],
       [2, 3],
       [4, 5]])

In [11]:
print(a)
a.T # transpose

[[0 1]
 [2 3]
 [4 5]]


array([[0, 2, 4],
       [1, 3, 5]])

#### index

In [18]:
print(a)
print(a[2][1]) #(2+1x 1+1 => 3x2 => 5)
a[1,0]          #(1+1x 0+1 => 2x1 => 2)

[[0 1]
 [2 3]
 [4 5]]
5


2

In [66]:
array = np.arange(0, 12).reshape(2, 3, 2)
print(array, "\n")
print("new\n", array[:, 1:, 1:], "\n")  # 1:2 x2:3 x2: 
print(array[0, 1, 0])  # 1x2x1 => 2

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] 

new
 [[[ 3]
  [ 5]]

 [[ 9]
  [11]]] 

2


In [82]:
# decrease dimension
print(array)
print(array[0][0][1])
array[0][0], array[0][0].ndim

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
1


(array([0, 1]), 1)

#### zeros, ones, eye, empty

In [97]:
z, o = np.zeros([2, 3 ,2]), np.ones([1, 3])
z, o

(array([[[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],
 
        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]]]), array([[ 1.,  1.,  1.]]))

In [99]:
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [114]:
np.empty([2, 2]) # actually, it's dummy data

array([[  6.94740926e-310,   4.67041775e-310],
       [  4.67041809e-310,   3.95252517e-322]])

#### like

In [105]:
print(z)
ls = np.ones_like(z)
ls

[[[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]]


array([[[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]]])

In [108]:
print(o)
ls = np.zeros_like(o)
print(ls)
print(ls.ndim, ls.shape)

[[ 1.  1.  1.]]
[[ 0.  0.  0.]]
2 (1, 3)


#### linspace, logspace

In [118]:
print(np.linspace(0, 24, 3)) 
np.logspace(2, 4, 3) # log=1, log =2, ,,, (start, end, interval)

[  0.  12.  24.]


array([   100.,   1000.,  10000.])