## np.random

In [2]:
np.random.seed(0) # control random number
rd = np.random.rand(3) #uniform
rdn = np.random.randn(3) #normal, gaussian distribution
print(rd)
print(rdn)

[ 0.5488135   0.71518937  0.60276338]
[-2.2683282   1.33354538 -0.84272405]


In [3]:
r = np.random.randint(10, size=(3, 4)) #integer, uniform
r

array([[6, 8, 8, 1],
       [6, 7, 7, 8],
       [1, 5, 9, 8]])

#### shuffle 

In [30]:
r = np.random.randint(10, size=(3, 4))
print(r)

np.random.shuffle(r)
print(r)

r = np.random.randint(10, size=(3, 4))
np.random.shuffle(r.reshape(1, 12))
r

[[7 0 3 8]
 [7 7 1 8]
 [4 7 0 4]]
[[4 7 0 4]
 [7 0 3 8]
 [7 7 1 8]]


array([[6, 4, 2, 4],
       [6, 3, 3, 7],
       [8, 5, 0, 8]])

#### choice

In [35]:
np.random.choice(5, 10, p=[0.1, 0.2, 0, 0.3, 0.4])
# p의 확률로 range(5)를 10개 추출

array([1, 3, 3, 4, 4, 4, 4, 0, 3, 3])

#### unique
- 데이터 구성 값과 값의 갯수 추출 (리스트형)

In [38]:
print(r)
index, count = np.unique(r, return_counts=True)
print(index) # 구성 값 리스트
print(count) # 각 값에 대한 갯수 리스트

[[6 4 2 4]
 [6 3 3 7]
 [8 5 0 8]]
[0 2 3 4 5 6 7 8]
[1 1 2 2 1 2 1 2]


#### stack

In [42]:
na1 = np.arange(6)
na2 = np.arange(6, 12)
print(na1, na1.shape)
print(na2, na2.shape)

na3 = np.stack((na1, na2)) #default axis = 0
print(na3, na3.shape)

na3 = np.stack((na1, na2), axis=1) #axis =1 -> vertically
na3

[0 1 2 3 4 5] (6,)
[ 6  7  8  9 10 11] (6,)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] (2, 6)


array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

### vstack, hstack, concatenate

In [87]:
na1 = np.random.randint(1, 16, (2, 2, 4))
print(na1)

[[[13 12 10  3]
  [14 10  5 10]]

 [[14 12  2  4]
  [ 3  5 14 10]]]


In [88]:
print(na1, na1.shape)
a = np.vstack(na1)
a, a.shape

[[[13 12 10  3]
  [14 10  5 10]]

 [[14 12  2  4]
  [ 3  5 14 10]]] (2, 2, 4)


(array([[13, 12, 10,  3],
        [14, 10,  5, 10],
        [14, 12,  2,  4],
        [ 3,  5, 14, 10]]), (4, 4))

In [90]:
a = np.hstack(na1)
a, a.shape

(array([[13, 12, 10,  3, 14, 12,  2,  4],
        [14, 10,  5, 10,  3,  5, 14, 10]]), (2, 8))

In [93]:
np.concatenate(na1)

array([[13, 12, 10,  3],
       [14, 10,  5, 10],
       [14, 12,  2,  4],
       [ 3,  5, 14, 10]])

In [94]:
np.concatenate(na1, axis=1)

array([[13, 12, 10,  3, 14, 12,  2,  4],
       [14, 10,  5, 10,  3,  5, 14, 10]])

### split

In [109]:
r = np.arange(5, 20)
print(r)
r1, r2, r3 = np.split(r, [3, 7])
r1, r2, r3

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


(array([5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17, 18, 19]))

#### vsplit, hsplit

In [123]:
r = np.random.randint(10, size=(4, 3))
r1, r2 = np.vsplit(r, [2])
print(r1, "\n\n", r2, "\n")
r3, r4 = np.hsplit(r, [2])
print(r3, "\n\n", r4)

[[8 1 5]
 [7 0 1]] 

 [[3 9 2]
 [8 2 4]] 

[[8 1]
 [7 0]
 [3 9]
 [8 2]] 

 [[5]
 [1]
 [2]
 [4]]


### sort

In [126]:
r1 = np.random.randint(10, size=(3, 3))
print(r1, "\n")
r1.sort()          #horizontal
print(r1, '\n')
r1.sort(axis=0)   # vertical
print(r1, '\n')

[[2 2 6]
 [4 6 0]
 [4 9 2]] 

[[2 2 6]
 [0 4 6]
 [2 4 9]] 

[[0 2 6]
 [2 4 6]
 [2 4 9]] 



### Datatype
- np data needs dtype to check datatype

In [127]:
na = np.array([True, False])
na.dtype, type(na)

(dtype('bool'), numpy.ndarray)