### Quiz

In [1]:
import numpy as np

##### 1. 5개의 1로 이루어진 정수데이터 타입의 벡터를 만드세요

In [3]:
data = np.ones(5, dtype = int)
data

array([1, 1, 1, 1, 1])

##### 2. 10개의 1로 이루어진 정수 데이터 타입의 벡터에서 마지막 3개의 데이터는 5가 들어있는 벡터를 만드세요

In [8]:
data = np.ones(10, dtype = int)
data[-3:] = 5
data

array([1, 1, 1, 1, 1, 1, 1, 5, 5, 5])

##### 3. 10에서 20까지의 데이터를 가지는 벡터를 만드세요

In [1]:
data = np.arange(10,20+1)
data

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

##### 4. 위 벡터의 순서를 바꾸세요

In [3]:
data[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

##### 5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요

In [5]:
data1 = np.arange(0, 8+1).reshape(3, 3)
data1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### 6. 위의 벡터에서  `[[4,5],[7,8]]`  행렬을 만드세요

In [7]:
data1[1:, 1:]

array([[4, 5],
       [7, 8]])

##### 7. 1에서 10까지의 데이터를 랜덤하게 가지는 3*4 행렬을 만드세요

In [17]:
rdata = np.random.randint(1, 10+1, (3, 4))
rdata

array([[ 6,  8,  8,  6],
       [ 7,  7,  3,  7],
       [10,  3,  5,  1]])

##### 8. 위에서 만든 행렬의 unique 한 숫자들 리스트와 각숫자의 갯수를 리스트로 나타내세요

In [23]:
np.unique(rdata, return_counts=True)

(array([ 1,  3,  5,  6,  7,  8, 10]), array([1, 2, 1, 2, 3, 2, 1]))

##### 9. 1에서 12까지에 숫자가 들어간 3*4 행렬을 만드시고 행과 열에 관계없이 데이터를 섞으세요

In [72]:
a = np.arange(1,12+1).reshape(3, 4)
print(a)
np.random.shuffle(a.reshape(1,12)[0])
a

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 5,  9, 12,  6],
       [10,  3,  1,  4],
       [ 8,  7,  2, 11]])

##### 10. 1부터 10까지의 랜덤한 데이터가 들어가는 `3*3`행렬을 만드시고 가장 아래에 위의 데이터를 모두 합한 `1*3`행렬을 추가해서 `4*3`행렬을 만드세요

In [131]:
data = np.random.randint(1, 10+1, (3, 3))
print(data)
sdata = data.sum(axis=0)
a = np.vstack((data, sdata))
a

[[2 4 4]
 [9 3 1]
 [7 8 7]]


array([[ 2,  4,  4],
       [ 9,  3,  1],
       [ 7,  8,  7],
       [18, 15, 12]])

##### 11. 10번문제의 결과로 나온 행렬데이터에서 평균값을 출력하고 평균값보다 큰 숫자들만 유니크한 리스트로 나열하세요 (평균값은 소수 둘째 자리까지만 나타내세요)

In [145]:
print("avg :", round(a.mean(), 2))
np.unique(a[a>a.mean()])

avg : 7.5


array([ 8,  9, 12, 15, 18])

##### 12. 1부터 20까지의 랜덤숫자를 가지는 5*5 행렬을 만드시고 최대값에는 숫자(MAX), 최소값에는 숫자(MIN)으로 행렬을 바꾸세요

In [93]:
a = np.random.randint(1,20+1, (5, 5))
print(a)

am = a.argmax()
m = a.max()
an = a.argmin()
n = a.min()

b = a.astype('U21').reshape(25, 1)


b[am] =  '{}(MAX)'.format(m)
b[an] = '{}(MIN)'.format(n)
b = b.reshape(5, 5)
b

[[ 5 10 19 10  3]
 [20 12 11 14 18]
 [ 3 18  8  3 18]
 [ 8 10 20 12 17]
 [15  4  7 11 19]]


array([['5', '10', '19', '10', '3(MIN)'],
       ['20(MAX)', '12', '11', '14', '18'],
       ['3', '18', '8', '3', '18'],
       ['8', '10', '20', '12', '17'],
       ['15', '4', '7', '11', '19']],
      dtype='<U21')

##### 13. 100에서 130까지의 랜덤 숫자를 가지는 8*8행렬을 만드시고 3의 배수에는 fiz, 5의 배수에는 buz, 3과 5의 배수는 fbz 문자를 출력하세요

In [134]:
a = np.random.randint(100, 130+1, (8, 8))
# count = len(na[(na%3 == 0) | (na%5 == 0)])
b = a.astype('U21')
b[(a%3 == 0)] = 'fiz'
b[(a%5 == 0)] = 'buz'
b[(a%15 == 0)] = 'fbz'

b

array([['buz', 'fiz', 'fiz', '109', '119', '109', 'buz', 'buz'],
       ['fiz', 'buz', '118', 'fiz', '104', 'fiz', '118', 'fiz'],
       ['103', '127', 'buz', '106', 'fiz', '113', '109', 'fiz'],
       ['fbz', 'buz', '112', 'fiz', '124', '116', 'buz', 'fbz'],
       ['106', '119', '121', 'buz', '112', 'fiz', 'fiz', 'fiz'],
       ['109', 'fiz', 'buz', 'buz', '103', 'fiz', '121', 'fbz'],
       ['fiz', 'fiz', 'fiz', 'buz', '101', '103', 'fbz', 'fiz'],
       ['118', 'buz', 'buz', 'fiz', '106', 'fiz', '106', 'fbz']],
      dtype='<U21')

##### 14. 리스트 컴프리헨션을 이용하여 아래와 같은 규칙을 갖는 행렬을 만드세요

In [214]:
input_number = int(input("number: "))
a1= np.ones((input_number, input_number))

for i in range (1, input_number+1):
    a = np.arange(i, input_number*i+1, i)
    a1[i-1] = a

a1 = a1.astype('int')
a1

number: 7


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 2,  4,  6,  8, 10, 12, 14],
       [ 3,  6,  9, 12, 15, 18, 21],
       [ 4,  8, 12, 16, 20, 24, 28],
       [ 5, 10, 15, 20, 25, 30, 35],
       [ 6, 12, 18, 24, 30, 36, 42],
       [ 7, 14, 21, 28, 35, 42, 49]])

In [250]:
input_number = int(input("number: "))

a1 =np.stack([list(range(i, input_number*i+1, i)) 
              for i in range(1, input_number+1)])
a1

number: 7


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 2,  4,  6,  8, 10, 12, 14],
       [ 3,  6,  9, 12, 15, 18, 21],
       [ 4,  8, 12, 16, 20, 24, 28],
       [ 5, 10, 15, 20, 25, 30, 35],
       [ 6, 12, 18, 24, 30, 36, 42],
       [ 7, 14, 21, 28, 35, 42, 49]])